### ISSUE TITLE
Giving a invalid enum name raises an error

### ISSUE THREAD

**Issue by DamirSvrtan** [infinum/enumerations#23]
I have an `DrugIntakeStatus` enum:

```ruby
class DrugIntakeStatus < Enumerations::Base
  value :pending, {}
  value :skipped, {}
  value :completed, {}
end
```

and a DrugIntake model:

```ruby
class DrugIntake < ApplicationRecord
  enumeration :status, class_name: DrugIntakeStatus
end
```

If I try to initialize my `DrugIntake` class with an invalid enum value, I get an internal Enumerations gem error:

```ruby
DrugIntake.new(status: :nonexistantvalue)
NoMethodError: undefined method `symbol' for nil:NilClass
from /Users/damirsvrtan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/enumerations-2.2.1/lib/enumerations.rb:89:in `block in define_setter_method'
```

Even if i set it to nil, I get the same error:

```ruby
DrugIntake.new(status: nil)
NoMethodError: undefined method `symbol' for nil:NilClass
from /Users/damirsvrtan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/enumerations-2.2.1/lib/enumerations.rb:89:in `block in define_setter_method'
```

**Comment by PetarCurkovic** [comment]
Fixed in #27 .
